model:
  name: "dinov2"  # Options: "dinov2", "vit", "resnet50"
  pretrained: true
  embedding_dim: 768  # For DINOv2/ViT
  image_size: 224

data:
  input_dir: "data/input"
  output_dir: "data/output"
  database_dir: "data/database"

indexing:
  index_file: "models/faiss_index.bin"
  metadata_file: "models/index_metadata.pkl"

training:
  batch_size: 32
  num_workers: 4

evaluation:
  top_k: [1, 5, 10, 20]

metadata:
  enabled: true  # Enabled metadata integration
  embedding_dim: 256
  fusion_method: "weighted"  # Options: "concat", "weighted"
  bom_dir: "data/output/bom"
  size_weight: 0.1  # Weight given to size similarity in reranking (0-1) - balanced for new algorithm

  # Autoencoder settings
  train_autoencoder: true  # Whether to train the autoencoder on data ingest
  hidden_dims: [512, 384]  # Hidden layer dimensions for encoder/decoder
  model_path: "models/metadata_autoencoder.pt"  # Path to save/load the trained model
  batch_size: 32  # Batch size for autoencoder training
  epochs: 50  # Number of training epochs
  learning_rate: 0.0001  # Learning rate for Adam optimizer
